name: Lighthouse CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm ci
      - run: npm run build --if-present || npm run build
      - name: Serve and run Lighthouse
        run: |
          npx http-server dist -p 4200 &
          sleep 3
          npx lighthouse http://localhost:4200 --preset=mobile --budgets-path=./lighthouse-budgets.json --quiet --chrome-flags='--headless --no-sandbox'
